config/routes.rb
Blogify::Application.routes.draw do
  

  resources :quote_posts

  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  get "post_types/new", to:"post_types#new"
  post "post_types/create", to:"post_types#create", as:"create_post_type"
  get "tags/new", to:"tags#new"
  post "tags/create", to:"tags#create", as:"create_tag"
  get "tags/:slug", to:"posts#by_tag", as:"by_tag"
  get "categories/new", to:"categories#new"
  post "categories/create", to:"categories#create", as:"create_category"
  get "categories/:slug", to:"posts#by_category", as:"by_category"

  post "comments/create", to:"comments#create"

  get "/search", to:"posts#search"
  resources :categories
  resources :posts
  resources :tags
  root 'posts#home'
  

end

app/views/home/_aside.html.erb
<aside>
  <div>
    <h2>Categories</h2>
    <% @categories.each do |cat| %>
      <%= link_to by_category_path(slug:cat.slug), class:"categories" do %>
      <%= cat.name %>
      <span class="categoties-number">
          <%= cat.posts.count %>
      </span>
      <% end %>
    <% end %>
  </div>
<!-- ======================================================Dribble============================= -->
    <div class="dribble">
      <h2>Dribble</h2>
      <a href="https://dribbble.com"><%= image_tag("rocket.png", class:"middle-img") %></a>
    </div>
<!-- ======================================================Twitter============================= -->
      <h2>Twitter</h2>
      <% @tweets.each do |tweet| %>
        <div class="twit">
          <p class="gray">
            <%= tweet.text %> 
          </p>
          <%= link_to tweet.user.name, tweet.user.url.to_s %>
        </div>
      <% end %>
<!-- ======================================================Pop posts============================= -->
    <h2>Popular posts</h2>
      <% @pop.each do |pop| %>
        <div class="popular-posts">
          <%= link_to post_path(pop) do %>
          <div style="background-image: url(<%= pop.image.url(:thumb) %>)" class="small-image"></div>
          <% end %>
          <p class="green"><%= l pop.date, :format => :long %></p>
          <p class="gray"><%= pop.title %></p>
        </div>
      <% end %>
<!-- ======================================================Rec comments============================= -->
    <h2>Recent Comments</h2>
      <% @recent_comments.each do |rec| %>
        <div class="recent-comments">
          <%= link_to rec.post do %>
          <div style="background-image: url(<%= rec.post.image.url(:thumb) %>)" class="small-image"></div>
          <% end %>
          <p class="green"><%= rec.author %></p>
          <% 
            if rec.comment.length > 50
              comment = rec.comment[0..40] + rec.comment[41..60].split(' ')[0] + '...'
            else
              comment = rec.comment
            end
           %>
          <p class="gray"><%= comment %></p>
        </div>
      <% end %>
<!-- ====================================================== tags ============================= -->
    <div class="tags">
      <h2>TAGS </h2>
      <% @tags.each do |tag| %>
        <%= link_to tag.name, by_tag_path(slug:tag.slug), class:"tag" %>
      <% end %>
    </div>
<!-- ====================================================== about ============================= -->
    <div class="about">
      <h2>About blogıfy</h2>
      <p class="gray">Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non  mauris vitae erat consequat auctor eu in elit. Sed non neque elit. Sed ut imperdiet nisi. Proin condimentum fermentum nunc. Etiam pharetra, erat sed fermentum feugiat, velit mauris egestas quam, ut aliquam massa nisl quis neque suspendisse in orci enim.</p>
    </div>
<!-- ====================================================== social ============================= -->
    <div class="social">
      <h2>keep social</h2>
      <a href="#" class="aside-icons"><%= image_tag("f.png")%></a><a href="#" class="aside-icons"><%= image_tag("f.png")%></a><a href="#" class="aside-icons"><%= image_tag("f.png")%></a><a href="#" class="aside-icons"><%= image_tag("f.png")%></a><a href="#" class="aside-icons"><%= image_tag("f.png")%></a><a href="#" class="aside-icons"><%= image_tag("f.png")%></a><a href="#" class="aside-icons"><%= image_tag("f.png")%></a><a href="#" class="aside-icons"><%= image_tag("f.png")%></a><a href="#" class="aside-icons"><%= image_tag("f.png")%></a><a href="#" class="aside-icons"><%= image_tag("f.png")%></a>
    </div>
    <div>
      <h2>search</h2>
      <%= form_tag("/search", method: "get") do %>
      <%= text_field_tag(:q, '',{ class:'aside-search', placeholder: 'Search...' }) %>
      <%= submit_tag("Search", class:'aside-submit') %>
      <% end %>
    </div>
    <div class="advertisement">
    </div>
</aside>

app/views/home/_nav.html.erb
<nav>
  <%= link_to "", root_path, class:"logo" %>
  <div class="container">
        <ul>
            <li><a href="#">HOME</a></li>
            <li><a href="#">ARCHIVE</a></li>
            <li><a href="#">CONTACT</a></li>
        </ul>
        <%= form_tag("/search", method: "get") do %>
            <%= text_field_tag(:q, '',{ class:'search', placeholder: 'Search...' }) %>
            <%= submit_tag("Search", class:'submit') %>
        <% end %>
        <div class="unnamed"></div>
        </div>
</nav>

app/views/home/index.html.erb
<div class="content">
  <% @posts.each do |post| %>
		<div class="post">
			<%= image_tag(post.image.url()) %>
      <%= link_to post, class:'title' do %>
        <h2><%= post.title %></h2>
      <% end %>
        <div class="data">
          <span class="post-meta-date">
            <%= image_tag("clock.png")%><%= l post.date, :format => :long %>
          </span>
          <span class="post-meta-comments">
            <%= image_tag("bubbles.png")%><%= pluralize(post.comments.count, "Comment") %>
          </span>
          <% if post.post_type %>
            <span class="post-meta-type">
              <%= image_tag(post.post_type.image.url()) %><%= post.post_type.name %>
            </span>
          <% end %>
        </div>
        <p class="gray"><%= post.preview %></p>
        <%= link_to 'Read more', post, class:'more' %>
		</div>
  <% end %>
  <% if @quote_post %>
  <div class="quote-post">
    <p class="thin"><%= @quote_post.quote %></p>
    <p><%= '--' + @quote_post.author %></p>
  </div>
  <% end %>
	<div class="link-post">
    <a href="#"><p class="gray">http://www.themeforest.net/user/SuitsTheme</p></a>
  </div>
	<div class="pagination">
    <% if @posts.current_page == 1 %>
      <%= link_to '<=', "#", class: 'page-active' %>
    <% else %>
      <%= link_to '<=', "/?page=#{@posts.current_page-1}", class: 'page' %>
    <% end %>
    <div class="numbers">
    <% (1..@posts.total_pages).to_a.each do |i| %>
      <% if i == @posts.current_page %>
        <%= link_to i, "/?page=#{i}", class: 'page-active' %>
      <% else %>
        <%= link_to i, "/?page=#{i}", class: 'page' %>
      <% end %>
    <% end %>
    </div>
    <% if @posts.current_page == @posts.total_pages %>
      <%= link_to '=>', "#", class: 'page-active right' %>
    <% else %>
      <%= link_to '=>', "/?page=#{@posts.current_page+1}", class: 'right page' %>
    <% end %>
	</div>
</div>
    