config/routes.rb
Blogify::Application.routes.draw do
  

  resources :quote_posts

  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  get "post_types/new", to:"post_types#new"
  post "post_types/create", to:"post_types#create", as:"create_post_type"
  get "tags/new", to:"tags#new"
  post "tags/create", to:"tags#create", as:"create_tag"
  get "tags/:slug", to:"posts#by_tag", as:"by_tag"
  get "categories/new", to:"categories#new"
  post "categories/create", to:"categories#create", as:"create_category"
  get "categories/:slug", to:"posts#by_category", as:"by_category"

  post "comments/create", to:"comments#create"

  get "/search", to:"posts#search"
  resources :categories
  resources :posts
  resources :tags
  root 'posts#home'
  

end

app/models/quote_post.rb
class QuotePost < ActiveRecord::Base
end

app/controllers/quote_posts_controller.rb
class QuotePostsController < ApplicationController
  before_action :set_quote_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :new, :create, :edit, :update, :destroy]

  # GET /quote_posts
  # GET /quote_posts.json
  def index
    @quote_posts = QuotePost.all
    render layout: 'admin'
  end

  # GET /quote_posts/1
  # GET /quote_posts/1.json
  def show
    render layout: 'admin'
  end

  # GET /quote_posts/new
  def new
    @quote_post = QuotePost.new
    render layout: 'admin'
  end

  # GET /quote_posts/1/edit
  def edit
    render layout: 'admin'
  end

  # POST /quote_posts
  # POST /quote_posts.json
  def create
    @quote_post = QuotePost.new(quote_post_params)

    respond_to do |format|
      if @quote_post.save
        format.html { redirect_to @quote_post, notice: 'Quote post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @quote_post }
      else
        format.html { render action: 'new' }
        format.json { render json: @quote_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quote_posts/1
  # PATCH/PUT /quote_posts/1.json
  def update
    respond_to do |format|
      if @quote_post.update(quote_post_params)
        format.html { redirect_to @quote_post, notice: 'Quote post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @quote_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quote_posts/1
  # DELETE /quote_posts/1.json
  def destroy
    @quote_post.destroy
    respond_to do |format|
      format.html { redirect_to quote_posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote_post
      @quote_post = QuotePost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_post_params
      params.require(:quote_post).permit(:quote, :author)
    end
end

app/helpers/quote_posts_helper.rb
module QuotePostsHelper
end

app/views/quote_posts/_form.html.erb
<%= form_for(@quote_post) do |f| %>
  <% if @quote_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote_post.errors.count, "error") %> prohibited this quote_post from being saved:</h2>

      <ul>
      <% @quote_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quote %><br>
    <%= f.text_area :quote %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quote_posts/edit.html.erb
<h1>Editing quote_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote_post %> |
<%= link_to 'Back', quote_posts_path %>

app/views/quote_posts/index.html.erb
<h1>Listing quote_posts</h1>

<table>
  <thead>
    <tr>
      <th>Quote</th>
      <th>Author</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @quote_posts.each do |quote_post| %>
      <tr>
        <td><%= quote_post.quote %></td>
        <td><%= quote_post.author %></td>
        <td><%= link_to 'Show', quote_post %></td>
        <td><%= link_to 'Edit', edit_quote_post_path(quote_post) %></td>
        <td><%= link_to 'Destroy', quote_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote post', new_quote_post_path %>

app/views/quote_posts/new.html.erb
<h1>New quote_post</h1>

<%= render 'form' %>

<%= link_to 'Back', quote_posts_path %>

app/views/quote_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quote:</strong>
  <%= @quote_post.quote %>
</p>

<p>
  <strong>Author:</strong>
  <%= @quote_post.author %>
</p>

<%= link_to 'Edit', edit_quote_post_path(@quote_post) %> |
<%= link_to 'Back', quote_posts_path %>